// new-client/src/components/Item/Item.tsx
import { FC, memo, useEffect, useState } from "react";
import Image from "next/image";
import styles from "./Item.module.scss";
import { getPlatformIcon } from "../../utils/format";
import { IProduct } from "../../types";
import Link from "next/link";
type ItemProps = {
  item: IProduct;
};

export const Item: FC<ItemProps> = memo(({ item }) => {
  const [preview, setPreview] = useState("");
  useEffect(() => {
    (async () => {
      if (item.imageIds.length > 0) {
        setPreview(
          item.imageIds[0].includes("http")
            ? item.imageIds[0]
            : `http://localhost:3001/api/images/assets/${item.imageIds[0]}`
        );
      }
    })();
  }, [item]);
  return (
    <Link href={`/products/${item.code}`}>
      <a className={styles.wrapper}>
        <div className={styles.item}>
          {preview != "" && (
            <img src={preview} width={270} height={270} alt={item.title} />
          )}
          <div className={styles.field}>
            <div className={styles.field__title}>Name</div>
            <div className={styles.field__value}>{item.title}</div>
          </div>
          <div className={styles.field}>
            <div className={styles.field__title}>Description</div>
            <div className={styles.field__value}>{item.description}</div>
          </div>
          <div className={styles.field}>
            <div className={styles.field__title}>Platforms</div>
            <div className={styles.field__value}>
              {item.platforms.map((platform) => {
                return (
                  <Image
                    src={getPlatformIcon(platform)}
                    width={20}
                    height={20}
                    alt={platform}
                    key={platform}
                  />
                );
              })}
            </div>
          </div>
          <div className={styles.field}>
            <div className={styles.field__title}>Rating</div>
            <div className={styles.field__value}>{item.rating || 0} / 5</div>
          </div>
          <div className={styles.field}>
            <div className={styles.field__title}>Reviews</div>
            <div className={styles.field__value}>
              {item.reviews.length || 0}
            </div>
          </div>
        </div>
      </a>
    </Link>
  );
});

// client/src/components/item/item.svelte
<script>
    import {Link} from "svelte-routing";
    import styles from "./item.css";
    export let item;
    let on = false;
</script>
<Link to="/products/{item.code}">
    <div class="item" class:itemhover={on} on:mouseenter={()=>on=true} on:mouseleave={()=>on=false}>
        <div class="content">
            <img src={item.imageIds[0].includes("http") ? item.imageIds[0] : `http://localhost:3001/api/images/assets/${item.imageIds[0]}`} alt="don't appear that image is loaded"/>
            <div class="textInItem">
                <span class="itemText"><span class="argument">Name: </span>{item.title}</span>
                <span class="itemText"><span class="argument">Desc: </span>{item.description.split('').slice(0, 25).join('')}
                    ...</span>
                <span class="itemText"><span class="argument">Platforms: </span>
                    {#each item.platforms as platform} <img class="platformimg"
                                                            src="/images/{platform}.png"
                                                            alt={platform}/>{/each}</span>
                <span class="itemText"><span class="argument">Rating: </span>{item.reviews.length > 0 ? Math.round(item.reviews.reduce((sum, a)=>{return sum + +a.rating}, 0) / item.reviews.length) : "No reviews"} / 5</span>
                <span class="itemText"><span class="argument">Reviews: </span>{item.reviews.length}</span>
                <span class="itemText price"><span class="argument priceText">Price: </span><span
                        class="priceValue">{item.price}</span></span>
            </div>
        </div>
    </div>
</Link>
