// new-client(don't work)/src/components/Profile/Profile.tsx
import { useAuth } from "../../hooks";
import styles from "./Profile.module.scss";
export const Profile = () => {
    const {user, isAuthenticated, login, logout} = useAuth();
    
    return <div className={styles.profile}>
        {isAuthenticated ? <div className={styles.user} onClick={logout}>
            <img src={`https://cdn.discordapp.com/avatars/${user.userid}/${user.userImageId}.png?size=128`} alt={user.userName} />
            <span>{user.userName}</span>
        </div> : <button className={styles.button} onClick={login}>Login</button>}
    </div>
}

// client/src/components/profile/profile.svelte
<script>
    import { createEventDispatcher } from 'svelte';
    import Cookies from 'universal-cookie';
    import styles from "./profile.css";
    const cookies = new Cookies();
    export let id;
    export let name;
    export let imgId;

    const dispatch = createEventDispatcher();
    function logout(){
        cookies.remove("token");
        dispatch('logout', {
            text: 'Hello!'
        });
    }
</script>

<div class="profile" on:click={logout}>
    <img src="https://cdn.discordapp.com/avatars/{id}/{imgId}.png?size=128" alt="sussy buka">
    <span>{name}</span>
</div>
